"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9xqsh*8#gqd)*^#k9807%@o96)wv&u@e#6yu7)9+oh_m9tjnx@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'yourdomain.com']  # Example for production

# Application definition
INSTALLED_APPS = [
    'relationship_app',
    'bookshelf',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'csp',  # Added for Content Security Policy support
]

AUTH_USER_MODEL = 'bookshelf.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Required for HTTPS redirects and HSTS
    'csp.middleware.CSPMiddleware',  # Added for Content Security Policy
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'  # Added for collecting static files in production

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Directory for uploaded files

# Authentication redirects
LOGIN_REDIRECT_URL = '/'  # Where to go after successful login
LOGOUT_REDIRECT_URL = 'login'  # Where to go after logout
LOGIN_URL = 'login'  # Where Django redirects unauthenticated users
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- HTTPS and Security Settings ---

# Redirect all non-HTTPS requests to HTTPS
# Ensures all traffic uses secure connections
SECURE_SSL_REDIRECT = True

# Enable HTTP Strict Transport Security (HSTS)
# Forces browsers to use HTTPS for one year (31536000 seconds)
SECURE_HSTS_SECONDS = 31536000
# Include all subdomains in HSTS policy
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# Allow site to be included in browsers' HSTS preload list
SECURE_HSTS_PRELOAD = True

# Ensure cookies are only sent over HTTPS
# Prevents session hijacking and CSRF token leakage over insecure connections
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Prevent browsers from MIME-sniffing responses
# Mitigates certain XSS attacks by enforcing declared Content-Type
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enable browser's built-in XSS filter
# Blocks rendering of pages if an XSS attack is detected
SECURE_BROWSER_XSS_FILTER = True

# Prevent site from being embedded in frames/iframes
# Protects against clickjacking attacks
X_FRAME_OPTIONS = 'DENY'

# --- Content Security Policy (CSP) Settings ---
# Requires 'django-csp' package and 'csp' in INSTALLED_APPS and MIDDLEWARE
# Mitigates XSS attacks by whitelisting trusted content sources
CSP_DEFAULT_SRC = ("'self'",)  # Only allow resources from the same origin
CSP_SCRIPT_SRC = ("'self'",)  # Only allow scripts from the same origin
CSP_STYLE_SRC = ("'self'",)  # Only allow stylesheets from the same origin
CSP_IMG_SRC = ("'self'", "data:")  # Allow images from self and data URIs
CSP_FONT_SRC = ("'self'",)  # Allow fonts from self
CSP_CONNECT_SRC = ("'self'",)  # Allow connections (fetch, XHR, WebSockets) from self
CSP_OBJECT_SRC = ("'none'",)  # Disallow <object>, <embed>, <applet>
CSP_BASE_URI = ("'self'",)  # Only allow <base> URLs from the same origin
CSP_FORM_ACTION = ("'self'",)  # Only allow form submissions to the same origin
CSP_FRAME_ANCESTORS = ("'self'",)  # Only allow embedding in iframes from the same origin

# Uncomment to allow external resources (e.g., for CDNs or Google Fonts)
# CSP_SCRIPT_SRC = ("'self'", "https://cdn.jsdelivr.net", "https://code.jquery.com")
# CSP_STYLE_SRC = ("'self'", "https://cdn.jsdelivr.net", "https://fonts.googleapis.com")
# CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")

# Optional: Enable CSP violation reporting
# CSP_REPORT_URI = "/csp-report/"