# Generated by Django 5.2.4 on 2025-07-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book entry'), ('can_change_book', 'Can change existing book entries'), ('can_delete_book', 'Can delete book entries')]},
        ),
    ]
